let adjectives = [
  "An Advanced",
  "An Agitated",
  "An Analytical",
  "An Angry",
  "An Anxious",
  "An Apathetic",
  "An Aristocratic",
  "An Astonishing",
  "An Astronomical",
  "An Astute",
  "A Baroque-styled",
  "A Basic",
  "A Behemoth",
  "A Bitter",
  "A Bored",
  "A Breathtaking",
  "A Brilliant",
  "A Broken-down",
  "A Byzantine",
  "A Captivating",
  "A Chivalrous",
  "A Clever",
  "A Colossal",
  "A Compact",
  "A Competent",
  "A Confident",
  "A Conflicted",
  "A Confused",
  "A Content",
  "A Cosmic",
  "A Crumbling",
  "A Crusading",
  "A Curious",
  "A Damaged",
  "A Dazzling",
  "A Decrepit",
  "A Depressed",
  "A Detached",
  "A Deteriorating",
  "A Dilapidated",
  "A Distracted",
  "A Dramatic",
  "A Drone-assisted",
  "A Dull",
  "An Ecstatic",
  "An Edwardian",
  "An Elated",
  "An Electrifying",
  "An Elizabethan",
  "An Enormous",
  "An Enthralling",
  "An Enthusiastic",
  "An Envious",
  "An Erudite",
  "An Ethereal",
  "An Euphoric",
  "An Exhilarating",
  "An Expansive",
  "An Explosive",
  "An Exuberant",
  "A Faded",
  "A Feudal",
  "A Fierce",
  "A Flawless",
  "A Focused",
  "A Formidable",
  "A Frayed",
  "A Freezing",
  "A Frustrated",
  "A Futuristic",
  "A Galactic",
  "A Gargantuan",
  "A Genius",
  "A Gifted",
  "A Gigantic",
  "A Gleaming",
  "A Gloomy",
  "A Glossy",
  "A Gothic",
  "A Grateful",
  "A Gripping",
  "A Hair-raising",
  "A Heraldic",
  "A Herculean",
  "A High-tech",
  "A Holographic",
  "A Hopeful",
  "A Huge",
  "An Immaculate",
  "An Immense",
  "An Imperial",
  "An Indestructible",
  "An Indifferent",
  "An Ingenious",
  "An Insecure",
  "An Insightful",
  "An Inspired",
  "An Intelligent",
  "An Intense",
  "An Intuitive",
  "An Inventive",
  "An Irritable",
  "A Joyful",
  "A Jumbo",
  "A Keen",
  "A Knowledgeable",
  "A Large",
  "A Learned",
  "A Luminous",
  "A Lush",
  "A Malfunctioning",
  "A Mammoth",
  "A Massive",
  "A Matte",
  "A Medieval",
  "A Meditative",
  "A Melancholic",
  "A Mesmerizing",
  "A Metallic",
  "A Mind-blowing",
  "A Mindful",
  "A Mint",
  "A Minuscule",
  "A Modular",
  "A Monastic",
  "A Monumental",
  "A Morose",
  "A Morphing",
  "A Multifunctional",
  "A Naive",
  "A Nano-enhanced",
  "A Neglected",
  "A Noble",
  "An Oblivious",
  "An Optimistic",
  "An Ornate",
  "An Overwhelmed",
  "A Peaceful",
  "A Pensive",
  "A Perceptive",
  "A Pessimistic",
  "A Petite",
  "A Phenomenal",
  "A Polished",
  "A Possessed",
  "A Preoccupied",
  "A Preserved",
  "A Pristine",
  "A Proficient",
  "A Quick-witted",
  "A Radiant",
  "A Ravaged",
  "A Ravenous",
  "A Regency-era",
  "A Relaxed",
  "A Renaissance",
  "A Resourceful",
  "A Restless",
  "A Revolutionary",
  "A Robust",
  "A Romanesque",
  "A Rugged",
  "A Ruined",
  "A Rusting",
  "A Satisfied",
  "A Savvy",
  "A Scholarly",
  "A Scratched",
  "A Self-repairing",
  "A Serene",
  "A Shabby",
  "A Shadowy",
  "A Sharp",
  "A Shrewd",
  "A Simple",
  "A Skilled",
  "A Sleek",
  "A Slow",
  "A Smart",
  "A Solar-powered",
  "A Sparkling",
  "A Spectacular",
  "A Spotless",
  "A Staggering",
  "A Startling",
  "A Steampunk",
  "A Stirring",
  "A Stressed",
  "A Sullen",
  "A Tarnished",
  "A Tattered",
  "A Telepathic",
  "A Terrifying",
  "A Threadbare",
  "A Thrilling",
  "A Tiny",
  "A Transparent",
  "A Tudor",
  "An Unaware",
  "An Unblemished",
  "A Universal",
  "An Unsophisticated",
  "An Untouched",
  "A Vandalized",
  "A Vast",
  "A Vibrant",
  "A Victorian",
  "A Weathered",
  "A Well-kept",
  "A Wise",
  "A Worn",
];
let colours = [
  { name: "Red", hex: "#FF0000" },
  { name: "Dark Red", hex: "#8B0000" },
  { name: "Light Red", hex: "#FF3333" },
  { name: "Deep Red", hex: "#800000" },
  { name: "Orange", hex: "#FFA500" },
  { name: "Dark Orange", hex: "#FF8C00" },
  { name: "Light Orange", hex: "#FFC04D" },
  { name: "Burnt Orange", hex: "#CC5500" },
  { name: "Yellow", hex: "#FFFF00" },
  { name: "Dark Yellow", hex: "#808000" },
  { name: "Light Yellow", hex: "#FFFF99" },
  { name: "Gold", hex: "#FFD700" },
  { name: "Green", hex: "#008000" },
  { name: "Dark Green", hex: "#006400" },
  { name: "Light Green", hex: "#66FF66" },
  { name: "Forest Green", hex: "#228B22" },
  { name: "Blue", hex: "#0000FF" },
  { name: "Dark Blue", hex: "#00008B" },
  { name: "Light Blue", hex: "#ADD8E6" },
  { name: "Sky Blue", hex: "#87CEEB" },
  { name: "Indigo", hex: "#4B0082" },
  { name: "Dark Indigo", hex: "#3D1F72" },
  { name: "Light Indigo", hex: "#6456B7" },
  { name: "Deep Indigo", hex: "#220066" },
  { name: "Violet", hex: "#8A2BE2" },
  { name: "Dark Violet", hex: "#9400D3" },
  { name: "Light Violet", hex: "#BF94E4" },
  { name: "Pale Violet", hex: "#D8BFD8" },
  { name: "Magenta", hex: "#FF00FF" },
  { name: "Dark Magenta", hex: "#8B008B" },
  { name: "Light Magenta", hex: "#FF99FF" },
  { name: "Rose", hex: "#FF007F" },
  { name: "Gray", hex: "#808080" },
  { name: "Dark Gray", hex: "#404040" },
  { name: "Light Gray", hex: "#C0C0C0" },
  { name: "Charcoal", hex: "#555555" },
  { name: "Teal", hex: "#008080" },
  { name: "Dark Teal", hex: "#004040" },
  { name: "Light Teal", hex: "#00CCCC" },
  { name: "Turquoise", hex: "#40E0D0" },
  { name: "Coral", hex: "#FF7F50" },
  { name: "Dark Coral", hex: "#FF6347" },
  { name: "Light Coral", hex: "#FFA07A" },
  { name: "Salmon", hex: "#FA8072" },
  { name: "Mauve", hex: "#BA55D3" },
  { name: "Dark Mauve", hex: "#9370DB" },
  { name: "Light Mauve", hex: "#E0B0FF" },
  { name: "Lavender", hex: "#E6E6FA" },
  { name: "Brown", hex: "#A52A2A" },
  { name: "Dark Brown", hex: "#663300" },
  { name: "Light Brown", hex: "#D2B48C" },
  { name: "Chocolate", hex: "#D2691E" },
  { name: "Fluoro Yellow", hex: "#CCFF00" },
  { name: "Fluoro Pink", hex: "#FF1493" },
  { name: "Fluoro Orange", hex: "#FFD700" },
  { name: "Fluoro Green", hex: "#00FF00" },
  { name: "Fluoro Blue", hex: "#00BFFF" },
  { name: "Ultraviolet", hex: "#9400D3" },
  { name: "Silver", hex: "#C0C0C0" },
  { name: "Bronze", hex: "#CD7F32" },
  { name: "White", hex: "#E6E6E6" },
  { name: "Black", hex: "#232323" },
];

let nouns = [
  "Adventurer",
  "Advisor",
  "AI Overlord",
  "Alchemist",
  "Alien",
  "Angel",
  "Anarchist",
  "Archaeologist",
  "Archer",
  "Archivist",
  "Assassin",
  "Astronaut",
  "Barbarian",
  "Berserker",
  "Bounty Hunter",
  "Break Dancer",
  "Bowman",
  "Centurion",
  "Champion",
  "Cleric",
  "Clone",
  "Commando",
  "Conquistador",
  "Cosmic Entity",
  "Counselor",
  "Crusader",
  "Curator",
  "Cyborg",
  "Demon",
  "Diplomat",
  "DJ",
  "Dragon",
  "Dragon Rider",
  "Druid",
  "Dwarf",
  "High Elf",
  "Examiner",
  "Explorer",
  "Fairy",
  "Galactic Emperor",
  "Graffiti Artist",
  "Ghost",
  "Gladiator",
  "Graduate",
  "Guardian",
  "Hunter",
  "Traveler",
  "Interstellar Merchant",
  "Inventor",
  "Knight",
  "Lecturer",
  "Legionnaire",
  "Librarian",
  "Mad Scientist",
  "Mage",
  "Marine",
  "Matador",
  "Mentor",
  "Mercenary",
  "Moderator",
  "Musketeer",
  "Mutant",
  "Necromancer",
  "Ninja",
  "Orc",
  "Paladin",
  "Pilot",
  "Pirate",
  "Pirate Captain",
  "Professor",
  "Punk",
  "Ranger",
  "Rebel Fighter",
  "Researcher",
  "Rogue",
  "Ronin",
  "Sailor",
  "Samurai",
  "Scholar",
  "Scientist",
  "Shaman",
  "Sniper",
  "Soldier",
  "Sorcerer",
  "Space Explorer",
  "Space Marine",
  "Space Pirate",
  "Spartan",
  "Spy",
  "Starship Pilot",
  "Student",
  "Superhero",
  "Technician",
  "Templar",
  "Thief",
  "Tiger",
  "Time Traveler",
  "Tutor",
  "Vampire",
  "Viking",
  "Warlock",
  "Warlord",
  "Warrior",
  "Werewolf",
  "Witch",
  "Wizard",
];

let locations = [
  "In An\nAirship",
  "On An\nAlien Planet",
  "In An\nAncient Colosseum",
  "In An\nAncient Forge",
  "In An\nAncient Temple Ruins",
  "In An\nApocalyptic Wasteland",
  "In An\nArctic Research Station",
  "In An\nAsteroid Spaceport",
  "In The\nAstral Plane",
  "In A\nBiodome Habitat",
  "Outside A\nCastle Ruins",
  "In A\nCelestial Observatory",
  "In A\nCelestial Palace",
  "In front Of\nA Futuristic Cityscape",
  "In A\nClockwork City",
  "In A\nCoral Labyrinth",
  "In A\nCoral Reef Kingdom",
  "Inside A\nCosmic Void",
  "In A\nCrystal Cave",
  "In A\nCrystal Citadel",
  "On Top Of A\nCrystal Mountain",
  "In A\nCyberpunk City",
  "In A\nDeep Sea Trench",
  "In A\nDeep Space Outpost",
  "In A\nDesert Oasis",
  "At A\nDimensional Crossroads",
  "Inside The\nDream Realm",
  "In A\nDystopian Megacity",
  "In An\nElemental Shrine",
  "In An\nEnchanted Forest",
  "At A\nFloating Fortress",
  "At A\nFloating Gardens",
  "At A\nFloating Market",
  "In A\nFloating Sky City",
  "In \nForgotten Catacombs",
  "In A\nFrontier Town",
  "In A\nGalactic Spaceport",
  "In A\nGarden Sanctuary",
  "In A\nGhost Town",
  "In A\nGlacial Fortress",
  "In A\nGraveyard",
  "In A\nHaunted Mansion",
  "In A\nHidden Cavern",
  "In A\nForest Sanctuary",
  "In A\nHidden Valley",
  "In A\nHolographic Cityscape",
  "In An\nIce Palace",
  "At An\nInterstellar Highway",
  "At An\nInterstellar Waystation",
  "In A\nJungle Canopy City",
  "In A\nJungle Temple",
  "In A\nLaboratory",
  "In A\nLabyrinth",
  "In A\nLibrary in the Clouds",
  "In A\nLunar Colony",
  "In A\nMartian Metropolis",
  "In A\nMedieval Village",
  "On Top A\nMountain Peak",
  "In A\nMushroom Forest",
  "In A\nMystical Grove",
  "In A\nParallel Dimension",
  "In A\nPirate Hideout",
  "In A\nPirate Shipwreck",
  "In A\nPocket Dimension",
  "In Front Of\nA Portal",
  "At A\nResearch Facility",
  "In A\nRobot Factory",
  "On Top\nSand Dunes",
  "In A\nUnderground Bunker",
  "In A\nShadowy Underworld",
  "Outside A\nSky Castle",
  "On A\nSolar Farm on Mars",
  "On A\nSpace Station",
  "In A\nSpaceship Graveyard",
  "In A\nSteampunk City",
  "In An\nIce Palace",
  "In A\nSubmarine Base",
  "In A\nLava Cavern",
  "In A\nSunken Treasure Ship",
  "At A\nTrading Post",
  "In Front Of\nThe Tree of Life",
  "In A\nTropical Paradise",
  "In An\nUnderground Bunker",
  "In An\nUnderwater City",
  "At A\nVolcanic Crater",
  "In A\nWizard's Tower",
  "In A\nZeppelin City",
  "In Front Of A\nFloating Crystal",
];

let verbs = [
  "Abseiling",
  "Acting",
  "Base jumping",
  "Playing Baseball",
  "Playing Basketball",
  "Biking",
  "Birdwatching",
  "Playing Board Games",
  "Boating",
  "Boxing",
  "Breakdancing",
  "Bungee Jumping",
  "Bursting Balloons",
  "Camping",
  "Carving",
  "Cave Diving",
  "Climbing",
  "Collapsing",
  "Composing",
  "Cooking",
  "Crying",
  "Crafting",
  "Playing Cricket",
  "Crumbling",
  "Cycling",
  "Dancing",
  "Designing",
  "Directing",
  "Disappearing",
  "Diving",
  "Drawing",
  "Engraving",
  "Erupting",
  "Evaporating",
  "Exploding",
  "Exploring",
  "Fencing",
  "Fighting",
  "Filmmaking",
  "Fishing",
  "Playing Football",
  "Free Diving",
  "Gardening",
  "Glassblowing",
  "Go-kart Racing",
  "Golfing",
  "Graffitiing",
  "Pole Vaulting",
  "Hiking",
  "Playing Ice Hockey",
  "Horseback riding",
  "Hoverboarding",
  "Hunting",
  "Hibernating",
  "Ice Skating",
  "Jet Skiing",
  "Jogging",
  "Jumping",
  "Doing Karaoke",
  "Kayaking",
  "Playing Laser Tag",
  "Meditating",
  "Metalworking",
  "Playing Miniature Golf",
  "Mountaineering",
  "Off-Roading",
  "Orienteering",
  "Doing Origami",
  "Swimming",
  "Paintballing",
  "Painting",
  "Paragliding",
  "Doing Parkour",
  "Photographing",
  "Picnicking",
  "Doing Pilates",
  "Plummeting",
  "Doing Pottery",
  "Printmaking",
  "Puppeteering",
  "Rafting",
  "Reading",
  "Rock Climbing",
  "Roller Skating",
  "Playing The Drums",
  "Playing The Guitar",
  "Playing The Violin",
  "Playing The Trumpet",
  "Playing Jazz Flute",
  "Running",
  "Robbing",
  "Sailing",
  "Sculpting",
  "Singing",
  "Skateboarding",
  "Skating",
  "Sketching",
  "Stretching",
  "Skiing",
  "Skydiving",
  "Slaying",
  "Slacklining",
  "Sleeping",
  "Snorkeling",
  "Snowboarding",
  "Spelunking",
  "Sprinting",
  "Stargazing",
  "Stealing Treasure",
  "Storytelling",
  "Making Sushi",
  "Surfing",
  "Swimming",
  "Doing Tai Chi",
  "Playing Tennis",
  "Trampolining",
  "Transforming",
  "Trekking",
  "Tumbling",
  "Rusting Away",
  "Vanishing",
  "Playing Video Games",
  "Playing Volleyball",
  "Making Pizza",
  "Whitewater Rafting",
  "Windsurfing",
  "Wine Tasting",
  "Woodworking",
  "Wrestling",
  "Writing",
  "Doing Yoga",
  "Zip-lining",
];
